spring:
  datasource:
    url: jdbc:h2:mem:testdb;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE;MODE=PostgreSQL
    username: sa
    password:
    driver-class-name: org.h2.Driver

  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    hibernate:
      ddl-auto: create-drop   # Hibernate creates schema from entities (fast)
    show-sql: false

  # Disable Flyway in tests (we use H2 + ddl-auto)
  flyway:
    enabled: false
  # Exclude pulsar configurations
  autoconfigure:
    exclude:
      - org.springframework.boot.pulsar.autoconfigure.PulsarAutoConfiguration